services:
  di-postgres:
    image: postgres
    container_name: di-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: didb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - di
volumes:
  pgdata:

networks:
  di:
    driver: "bridge"
